## 8bit AVR compilation code

# project-dependent config
arch="atmega328p"
files=["build_bootloader/bootloader.c","build_bootloader/common/base_protocol.c"]

VariantDir('build_bootloader','src')

# common code
env=Environment(AS="avr-as",CC="avr-gcc",
    CCFLAGS="-D F_CPU=6000000L -mmcu=%s -std=gnu99 -Wall -O2"%arch,
    LINKFLAGS="-Wl,--section-start=.text=0x3800 -mmcu=%s"%arch)


env.Append(BUILDERS=
    {"Copy":Builder(action="avr-objcopy $SOURCE -O ihex $TARGET")
    ,"Dump":Builder(action="avr-objdump -dSr $SOURCE > $TARGET")
#    ,"Write":Builder(action="avrdude -p m328p -c arduino -P /dev/ttyUSB1 -U flash:w:$SOURCE:i")
    ,"WriteLoader":Builder(action="sudo avrdude -p m328p -c usbasp -U flash:w:$SOURCE:i")
    })

env.Alias('write',env.WriteLoader(None,'build_bootloader/fw.hex'))
env.Alias('compile',env.Program('build_bootloader/fw.elf',files))
env.Alias('compile',env.Copy('build_bootloader/fw.hex','build_bootloader/fw.elf'))
env.Alias('compile',env.Dump('build_bootloader/disasm.S','build_bootloader/fw.elf'))

env.Default('compile')



